### ISSUE TITLE
Consistently crashes during Tutorial

### ISSUE THREAD

**Issue by BlazingTwist** [hictooth/WildSkies#1]
Crash occurs when trying to feed the Deadly Nadder, before you unlock your first achievement.
I'm assuming the issue is that the game tries to call either of these externals
* cnGameTracking
* AchievementUnityComm.doSendStat
* AchievementUnityComm.doUnityGameStarted
* AchievementUnityComm.doUnityLoaded

I've seen that you're already handling most of those calls, except for `AchievementUnityComm.doSendStat`
In fact, adding the doSendStat function to your index.js fixes the crashes.

If it helps you, further external Calls would be
* AchievementModule.onOpenWindow
* cnlaGames.notifyAction (used when the selected locale is *not* EN)

**Comment by BlazingTwist** [comment]
On a slightly less related note, I'm working on a mod that enables saving locally as well as disabling the external calls.
It's running fine in both Flashpoint and your Client.
Actually, I much prefer the standalone-ness of your Client, would you be interested in Collaborating?

**Comment by hictooth** [comment]
Thanks to you (and others!) for spotting this - I broke rule #1 here of "Don't do a quick improvement and publish without testing!".

It was to do with those messages - although I was catching them, I was then writing to a non-existent div, causing it to crash. Oops!

v2.0.2 is uploaded now, which (actually!) works.

**Comment by hictooth** [comment]
Re. collaborating, that would be great! It's been nice the past couple of days to discover that others remember and like _Wild Skies_ too.

You're implying you've managed to decompile, **and then recompile** the game? If so, nice - I never got that far (although I really know nothing of Unity dev so that's probably not a surprise).

**Comment by BlazingTwist** [comment]
Your client actually was the last piece of the puzzle for me.
I had to supply the default assemblies myself, but since they had a different version, the game would reject loading any classes that were compiled with my assemblies.
Supplying the ones your client uses instead solved that.

Everything else is rather simple.
QuickBMS script for unpacking the .unity3d bundle,
Dnspy to modify the assemblies,
Custom Tool for repacking the bundle.

... a github issue seems like the wrong place for this, do you have a platform you prefer for communicating?

**Comment by davidferguson** [comment]
If you have Discord them I'm `@hictooth#7836` on there.

**Comment by hictooth** [comment]
If you have Discord them I'm `@hictooth#7836` on there.
