### ISSUE TITLE
Pressing 6 summons the Thunderdrum instead of the Scauldron, I don't even have the Thunderdrum unlocked.

### ISSUE THREAD

**Issue by Vampyridon** [hictooth/WildSkies#11]
I have the Deadly Nadder and the Scauldron unlocked, yet for some reason pushing the 6 key summons the Thunderdrum for me to ride, despite me not having unlocked it or even having bought the crab cage.

I'd also like to add that it won't let me summon the Scauldron with any of the other number keys, so I assume it and the Thunderdrum have their summoning keys mixed up somehow?

![I do not have the thunderdrum unlocked](https://user-images.githubusercontent.com/111443816/208409980-61d7ab53-f864-42a2-bc56-6d2de964018e.png)
As you can see only the Deadly Nadder and the Scauldron are unlocked, not the Thunderdrum.
![no crab cage 2](https://user-images.githubusercontent.com/111443816/208410494-c59db089-cd5d-47e3-bdf1-8ae004093a2f.png)
I do not own the Crab Cage required to tame the Thunderdrum.
![me on the thunderdrum](https://user-images.githubusercontent.com/111443816/208410023-d794005a-1810-4010-96b4-67f6f979f615.png)
Me riding the Thunderdrum

**Comment by Vampyridon** [comment]
Sorry for like the 50 edits btw

**Comment by hictooth** [comment]
(late reply, but here goes anyway)
...well that's an interesting bug. However, this is just a port of the Wild Skies game, with all its bugs and all. This bug presumably existed in the original game, and therefore it exists here.
