### ISSUE TITLE
i cant find the exe

### ISSUE THREAD

**Issue by ghost** [hictooth/WildSkies#4]
idk if im just dumb but i really dont know how to make it work, im sorry to make an issue just to ask that but i want to play this game so so so so bad and i have to came for help
so the question is when you say "run the wildskies.exe", but I just can't find any .exe in the zip (I already extracted it) and i looked in every file twice and once more
if im missing something i dont know what it is, thats my first time in this website and im not very great with computers and stuff but i really want to play this game and sorry for the ignorance but can you tell me how to find this .exe or what exactly am I missing to run this game? thanks already and again sorry ><'

**Comment by hictooth** [comment]
A few people have had issues with this, so it's probably my fault for not making it clearer.

The zip you want to download isn't the code zip, it's the release zip, which is linked under the **Getting Started** header. I've linked these below for you:
- [Windows](https://github.com/hictooth/WildSkies/releases/latest/download/WildSkiesWindows.zip)
- [Mac](https://github.com/hictooth/WildSkies/releases/latest/download/WildSkiesMac.zip)

Unzip that, and the exe will be in there.
