### ISSUE TITLE
can not find WildSkies.exe

### ISSUE THREAD

**Issue by fezbot303** [hictooth/WildSkies#5]
I just wanted to check with you to make sure I'm doing it all right, I followed the info you give on how to set it all up, once I have downlouded it all and extracted it all I cant seem to find the exe file you take about, I'm on Windows 10 if that helps at all

**Comment by hictooth** [comment]
Ah sorry, this is mainly my fault for not making it clear that you should be downloading the release zip, not the code zip. I've changed the page so it's hopefully a bit clearer - let me know if there are any other issues!
